### ISSUE TITLE
[BUG(?)] Can't send messages. Need help.

### ISSUE THREAD

**Issue by Vantagevoin** [AmmoniaM/Spermack#11]
I've followed everything in the tutorial but my messages will not get sent for whatever reason. When I clicked the quill to send, it turned into the hourglass for 1s before turning back to the quill regardless of the settings I chose in the OpenAI settings menu, except for enabling streaming. The icon was stuck in hourglass mode for what seemed to be forever if I enabled streaming. Of course, I disabled NSFW first setting.

Here's what my terminals look like.

![image](https://user-images.githubusercontent.com/68242614/235614936-5e96bb5e-8425-48fe-a09c-4170183d0733.png)

Using the latest commit. Any solution?

**Comment by bfs15** [comment]
If you updated SillyTavern (my aisu branch) branch between around: Mon May 01 2023 22:15:55 GMT+0000   -   Tue May 02 2023 05:19:11 GMT+0000
that's the reason. Sorry.

If not, I can't think of anything right now, so if updating aisu again doesn't work
So send a screenshot of your settings

**Comment by Vantagevoin** [comment]
It works now, thanks!

**Comment by bfs15** [comment]
> If I may ask, what are the differences between using CI through Slack and Poe?

On poe, the non-instant Claude is limited

> Lastly, should I be worried about this?

maybe
