### ISSUE TITLE
Error of: Retry, reply was too small retries left

### ISSUE THREAD

**Issue by AsadaKintoki** [AmmoniaM/Spermack#13]
at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
Retry, reply was too small retries left: 5
+ Retrying: retryable error found while attempted to streamResponse: Retry, reply was too small
{ ok: true, keep_input: false }
Connected to WebSocket

Hi, Facing the above issue while sending msg, I'm able to see the response in SillyTavern cmd however Spermack giving this error and UI also not have new message...

**Comment by bfs15** [comment]
where those two first lines the whole stack?
It caught a retryable error, so it was supposed to retry after that (send another batch of messages to Claude)
>I'm able to see the response in SillyTavern
an actual response or an error one? what does slack look like?

**Comment by AsadaKintoki** [comment]
This part is last three sentence, the whole log contain some my local information so I only copy this part, I can modify and resend later.
So after I enter message, in Claude looks like below


Human: [Main Prompt]

[Then NSFW Prompt

Human: […]

Assistant: […]]


[Character setting]


Human: [Start a new chat]


Human: (Greeting word to character but not input my me)


Human: (Another greeting word to character but not input my me)


Assistant: Some response, not show in SillyTraven


Human: [Start a new chat]


Human: Hello(This also not input by me)


Assistant: Some response, not show in SillyTraven


Human: [Start a new chat]


Assistant: [Response correct but still not show in SillyTraven ]


Human: [My replay]


Human: [System note: The Jailbreak Prompt]



Then I see this message repeat send to Claude, eventually Errored out. It does contain right response every time, but seems not be catch and not flow to SillyTraven


I can provide more detail if needed

________________________________
发件人: Aisu Wata ***@***.***>
发送时间: Wednesday, May 3, 2023 12:06:10 PM
收件人: AmmoniaM/Spermack ***@***.***>
抄送: AsadaKintoki ***@***.***>; Author ***@***.***>
主题: Re: [AmmoniaM/Spermack] Error of: Retry, reply was too small retries left (Issue #13)


where those two first lines the whole stack?
It caught a retryable error, so it was supposed to retry after that (send another batch of messages to Claude)

I'm able to see the response in SillyTavern

an actual response or an error one? what does slack look like?

―

**Comment by bfs15** [comment]
first, when did you last update Spermack and SillyTavern?

**Comment by AsadaKintoki** [comment]
Should be like 8 hours ago. I did earlier today.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Aisu Wata ***@***.***>
发送时间: Wednesday, May 3, 2023 12:27:23 PM
收件人: AmmoniaM/Spermack ***@***.***>
抄送: AsadaKintoki ***@***.***>; Author ***@***.***>
主题: Re: [AmmoniaM/Spermack] Error of: Retry, reply was too small retries left (Issue #13)


first, when did you last update Spermack and SillyTavern?

―

**Comment by bfs15** [comment]
If it repeated and eventually errored out it just means it ran out of retries and you have to try again

It might be your settings, by default, it filters small messages because they are likely refusals to cooperate.
If the responses you are expecting are small, you have to remove that feature.
check the settings with retry in their name, the variable names should be self explanatory.

**Comment by AsadaKintoki** [comment]
oh I see, Sounds good, I will try it once back to home and update here :)

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Aisu Wata ***@***.***>
发送时间: Wednesday, May 3, 2023 12:29:32 PM
收件人: AmmoniaM/Spermack ***@***.***>
抄送: AsadaKintoki ***@***.***>; Author ***@***.***>
主题: Re: [AmmoniaM/Spermack] Error of: Retry, reply was too small retries left (Issue #13)


If it repeated and eventually errored out it just means it ran out of retries and you have to try again

It might be your settings, by default, it filters small messages because they are likely refusals to cooperate.
If the responses you are expecting are small, you have to remove that feature.
check the settings with retry in their name, the variable names should be self explanatory.

―

**Comment by AsadaKintoki** [comment]
After change minimum_response_size everything works perfectly now. Thanks for helping!
One suggestion, maybe can add configure for this part in readme? Just in case someone else may encounter the same behavior.
Anyway, my issue is solved, thanks for helping again!

**Comment by bfs15** [comment]
suggestion added!
