### ISSUE TITLE
Contradiction in readme

### ISSUE THREAD

**Issue by Weblure** [AmmoniaM/Spermack#14]
The readme states "Current Spermack build expects you to use this SillyTavern branch: https://github.com/bfs15/SillyTavern/tree/aisu"

Yet, as of a few hours ago, the mindbreaking instructions were changed to say "Update Tavern: https://github.com/Cohee1207/SillyTavern"

It's unclear which fork we should be using.

**Comment by Weblure** [comment]
Scratch the first part, I dragged my old config file in without checking for changes

**Comment by bfs15** [comment]
thx, I missed that
it doesn't matter anymore because my changes were merged
