### ISSUE TITLE
Suggestion : Using "Human" instead of "System Note" for system role?

### ISSUE THREAD

**Issue by random-username-423** [AmmoniaM/Spermack#7]
I read documents on anthropic website, and it says there's only "Human:" and "Assistant:" role.

> Anthropic document : Claude has been trained and fine-tuned using RLHF (reinforcement learning with human feedback) methods on Human: and Assistant: data like this, so you will need to use these prompts in the API in order to stay “on-distribution” and get the expected results.

iirc even gpt-3.5-turbo is very shitty about system role unlike gpt-4, even though gpt-3.5-turbo offically support system role.
The reason seems like turbo is not fully trained with system role.

> OpenAI document : gpt-3.5-turbo-0301 does not always pay strong attention to system messages. Future models will be trained to pay stronger attention to system message

So... I can't imagine how much claude is bad at system role thingy. It can be more shit than turbo.
I wish people use "Human" for system role.

**Comment by bfs15** [comment]
Interesting, I'll add a config setting so you can change the name and test that out

**Comment by bfs15** [comment]
Feature added, test it out

**Comment by random-username-423** [comment]
Thank you very much!

**Comment by bfs15** [comment]
Since you are interested in minmaxing this, the config
`include_assistant_tag`
decides whether Assistant: is added at the end of  your message.
I added this because I suspect it's unnecessary or even doubling. Because Slack might already reasonably add this on their end, however they input the feed to Claude.
check it out

**Comment by bfs15** [comment]
The above left clear, but I'm curious about this stuff too, so if you have any thoughts on what you prompted with these settings, comparatively, please leave a comment.

**Comment by bfs15** [comment]
I reopened because it's related. I also because I hope I have the input of @random-username-423
currently, as OpenAI does, chat examples are sent as: example_user, example_assistant.
I just now noticed that this is not changed in Spermack

I can change them simply to example_Human, but is that the Claude specs?

**Comment by random-username-423** [comment]
In case of ChatML (gpt-3.5-turbo and gpt4), OpenAI clarify that "name" field can be existed.
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb
> Messages can also contain an optional name field, which give the messenger a name. E.g., example-user, Alice, BlackbeardBot. Names may not contain spaces.

>    messages=[
        {"role": "system", "content": "You are a helpful, pattern-following assistant that translates corporate jargon into plain English."},
        {"role": "system", "name":"example_user", "content": "New synergies will help drive top-line growth."},
        {"role": "system", "name": "example_assistant", "content": "Things working well together will increase revenue."},
        {"role": "system", "name":"example_user", "content": "Let's circle back when we have more bandwidth to touch base on opportunities for increased leverage."},
        {"role": "system", "name": "example_assistant", "content": "Let's talk later when we're less busy about how to do better."},
        {"role": "user", "content": "This late pivot means we don't have time to boil the ocean for the client deliverable."},
    ],

Meanwhile, In case of claude, anthropic clarify there should be only "human" and "assistant".
https://console.anthropic.com/docs/troubleshooting/checklist

> The only speakers are Human: and Assistant:, the text starts with a human and ends with an assistant, and each speaker oscillates (i.e. no Human: followed by Human:)

Examples are provided with only human and assistant too.
https://console.anthropic.com/docs/prompt-design/being-explicit

> Human: Think of a funny collective noun for dancers.
　
Assistant: A pirouette of dancers.
　
Human: Think of a funny collective noun for hipsters.
　
Assistant: A fedora of hipsters.
　
Human: Think of a funny collective noun for engineers.
　
Assistant: A nerd herd of engineers.
　
Human: Think of a funny collective noun for nurses.
　
Assistant:

In my opinion,
example_user should be converted into Human,
example_assistant should be converted into Assistant.

**Comment by bfs15** [comment]
Absolutely perfect @random-username-423 , newest update reflects all above.
and config changed to:

  ```
  rename_roles: {
    'user': 'Human',
    'assistant': 'Assistant',
    'system': 'Human',
  },
  ```
 The Mindbreak is so good. Thank you.
