### ISSUE TITLE
Syntax error related to CLAUDE_MEMBER_ID variable in config.js file

### ISSUE THREAD

**Issue by ixvjlv** [AmmoniaM/Spermack#8]
I have recently tried updating and running your Spermack, and I encountered an issue related to the CLAUDE_MEMBER_ID variable in the config.js file. Although your website says to leave it empty, I keep getting syntax errors when I do so. Here is the error message:

C:\AI\Spermack>call npm install

up to date, audited 18 packages in 663ms

found 0 vulnerabilities
C:\AI\Spermack\config.js:6
  CLAUDE_MEMBER_ID: "",
  ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier 'CLAUDE_MEMBER_ID'
[90m    at internalCompileFunction (node:internal/vm:73:18)[39m
[90m    at wrapSafe (node:internal/modules/cjs/loader:1195:20)[39m
[90m    at Module._compile (node:internal/modules/cjs/loader:1239:27)[39m
[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:1133:32)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:972:12)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1157:19)[39m
[90m    at require (node:internal/modules/helpers:119:18)[39m
    at Object.<anonymous> [90m(C:\AI\Spermack\[39mutils.js:7:5[90m)[39m
[90m    at Module._compile (node:internal/modules/cjs/loader:1275:14)[39m

Node.js v19.9.0

**Comment by bfs15** [comment]
very likely the line above it has no comma (",") at the end of the line

**Comment by bfs15** [comment]
this is an error of the javascript parser, meaning it couldn't even understand your config file, not a problem with the code
